services:
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    environment:
      TZ: Asia/Tokyo
      BINDING: 0.0.0.0
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: password
      PORT: 3000
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/com_app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - postgres
      - redis
  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: password
    command: bundle exec sidekiq
    volumes:
      - .:/com_app
    depends_on:
      - postgres
      - redis

volumes:
  postgres:
  redis:
